### ISSUE TITLE
vim starts in replace mode

### ISSUE THREAD

**Issue by andreasmischke** [tpope/vim-pathogen#102]
Since using pathogen, vim always starts in replace mode (Shift-R from normal mode).
How can I disable that behaviour?

My environment: Windows 7, cygwin, vim 7.3, pathogen 2.2

**Comment by Carlodf** [comment]
Same issue with:
`nnoremap <silent> <Esc> :nohlsearch<cr>`
remapping to something else fixed the issue.
Personally I replaced it with
`nnoremap <silent> <leader>/ :nohlsearch <cr>`

**Comment by Zabanaa** [comment]
Thanks a lot @Carlodf I did just that and it fixed the issue for me.

I'm on xubuntu 16.04 - gnome terminal - vim 8

cheers

**Comment by AstroProfundis** [comment]
I can confirm this issue been fixed as @Carlodf suggested. Thanks a lot!

I'm running ArchLinux with vim 8.0.628, and the issue is fixed by commenting out this line in my .vimrc:
`nnoremap <esc> :nohl<cr>`

So the question now becomes: how can I continue use <ese> as `:nohl` if that's my favorite?

**Comment by tpope** [comment]
If you really want to get to the bottom if it, you'll need to tear apart pathogen.vim itself and try to figure out what line causes the issue.

**Comment by noytzach** [comment]
@Carlodf's fix works for me. Thanks.

commenting out my nmap of <ESC> to :nohlsearch solved the problem.

**Comment by magks** [comment]
@AstroProfundis 
I replaced it with 
`nnoremap <esc><esc> :nohl<cr>`
and this worked for fixing the replace mode issue while still being somewhat close to the <ESC> mapping. Just a doubletap on the escape instead of one. Not too bad if the capsLock key has been swapped with escape on your keyboard.

**Comment by goerz** [comment]
For what it's worth, I've had the same problem of `nnoremap <silent> <Esc> :nohlsearch<cr>` causing vim to start in REPLACE mode (unrelated to pathogen). This only happened for `TERM=xterm*`.

I was able to get around the problem by appending the contents of https://gist.github.com/goerz/36015f27c2a5423c64a5f9dc03865f2c to my vimrc.
