### ISSUE TITLE
Pathogen not loading plugins

### ISSUE THREAD

**Issue by MIRAMAXED** [tpope/vim-pathogen#110]
Hello! I'm installing vim 7.4, and i'm installing vim-pathogen, following instructions, but plugins not loading :( May be i do something wrong? That's is my vimrc: http://pastebin.com/ZKn0j6R3

P.S. Sorry for my english...

**Comment by kochjamesr** [comment]
Hey I'm having the same sort of issue with ubuntu 16.04 vim 7.4.
i have a ~/.vimrc file which does not recognize any plugins when sourced.

output of '  :scriptnames  ':

  1: /usr/share/vim/vimrc
  2: /usr/share/vim/vim74/debian.vim
  3: /usr/share/vim/vim74/syntax/syntax.vim
  4: /usr/share/vim/vim74/syntax/synload.vim
  5: /usr/share/vim/vim74/syntax/syncolor.vim
  6: /usr/share/vim/vim74/filetype.vim
  7: ~/.vimrc
  8: /usr/share/vim/vim74/syntax/nosyntax.vim
  9: ~/.vim/autoload/pathogen.vim
 10: /usr/share/vim/vim74/ftoff.vim
 11: ~/.vim/bundle/delimitMate/plugin/delimitMate.vim
 12: ~/.vim/bundle/delimitMate/autoload/delimitMate.vim
 13: ~/.vim/bundle/vim-noscrollbar/plugin/noscrollbar.vim
 14: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
 15: /usr/share/vim/vim74/plugin/gzip.vim
 16: /usr/share/vim/vim74/plugin/logiPat.vim
 17: /usr/share/vim/vim74/plugin/matchparen.vim
 18: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 19: /usr/share/vim/vim74/plugin/rrhelper.vim
 20: /usr/share/vim/vim74/plugin/spellfile.vim
 21: /usr/share/vim/vim74/plugin/tarPlugin.vim
 22: /usr/share/vim/vim74/plugin/tohtml.vim
 23: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 24: /usr/share/vim/vim74/plugin/zipPlugin.vim

these return nothing but have no errors:

call pathogen#infect('bundle/{}')
call pathogen#infect('bundle/*')

output of  '  :echo glob("~/.vim/bundle/*")  ':

/home/jamesson/.vim/bundle/delimitMate
/home/jamesson/.vim/bundle/vim-noscrollbar

output of '  :echo pathogen#glob_directories("~/.vim/bundle/*")  ':

['/home/jamesson/.vim/bundle/delimitMate', '/home/jamesson/.vim/bundle/vim-noscrollbar']

output of '  set rtp?  ':

runtimepath=~/.vim,~/.vim/bundle/*,~/.vim/bundle/delimitMate,~/.vim/bundle/delimitMate/bundle/*,~/.vim/bundle/vim-noscrollbar,~/.vim/bundle/vim-noscrollbar/bundle/*,/var/lib/vim/addons,/va
r/lib/vim/addons/bundle/*,/usr/share/vim/vimfiles,/usr/share/vim/vimfiles/bundle/*,/usr/share/vim/vim74,/usr/share/vim/vim74/bundle/*,/usr/share/vim/vimfiles/bundle/*/after,/usr/share/vim/vi
mfiles/after,/var/lib/vim/addons/bundle/*/after,/var/lib/vim/addons/after,~/.vim/bundle/*/after,~/.vim/after

**Comment by priyankthakkar** [comment]
> Had the same issue on Win7 and Debian moved ~/.vim/.vimrc to ~/.vimrc (debian) and ~/vimfiles/_vimrc to ~/_vimrc (Win7) now everything works, thanks.

Thanks to Darius Kucinskas 👍 
This actually worked for my windows 10. All had to do for my gvim was rename ~/.gvimrc to _vimrc and move it under ~/vimfiles

After doing that, for the gvim shortcut i passed and arg, gvim.exe -u ~/vimfiles/_vimrc and pathogen started loading plugins. and this loads my _vimrc first

  1: P\vimfiles\_vimrc
  2: P:\vimfiles\autoload\plug.vim
  3: C:\NotBackedUp\Packages\Scoop\apps\vim\current\filetype.vim
  4: C:\NotBackedUp\editor\plugged\vim-polyglot\ftdetect\polyglot.vim
  5: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\css.vim
  6: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\graphql.vim
  7: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\html.vim
  8: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\javascript.vim
  9: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\json.vim
 10: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\less.vim
 11: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\markdown.vim
 12: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\scss.vim
 13: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\typescript.vim
 14: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\vue.vim
 15: C:\NotBackedUp\editor\plugged\vim-prettier\ftdetect\yaml.vim
 16: C:\NotBackedUp\Packages\Scoop\apps\vim\current\menu.vim
 17: C:\NotBackedUp\Packages\Scoop\apps\vim\current\autoload\paste.vim
 18: C:\NotBackedUp\Packages\Scoop\apps\vim\current\ftplugin.vim
 19: C:\NotBackedUp\Packages\Scoop\apps\vim\current\indent.vim
 20: C:\NotBackedUp\Packages\Scoop\apps\vim\current\syntax\syntax.vim
 21: C:\NotBackedUp\Packages\Scoop\apps\vim\current\syntax\synload.vim
 22: C:\NotBackedUp\Packages\Scoop\apps\vim\current\syntax\syncolor.vim
 23: C:\NotBackedUp\Packages\Scoop\apps\vim\current\syntax\nosyntax.vim
 24: C:\NotBackedUp\editor\plugged\oceanic-next\colors\OceanicNext.vim
