### ISSUE TITLE
Old versions of vim hang on start unless $VIMBLACKLIST is non empty

### ISSUE THREAD

**Issue by marknsikora** [tpope/vim-pathogen#118]
Bug was introduced in commit 9a40364c606039cacff0f61366851d0a0e53a22e. When the VIMBLACKLIST env var is empty, startup hangs indefinitely in the pathogen#is_disabled function. Only seems to be an issue in old versions of vim. Version 7.0.237 has this problem but 7.4 series does not.

**Comment by ameidatou** [comment]
This still doesn't work in my vim:
VIM - Vi IMproved 7.0 (2006 May 7, compiled Nov 12 2010 05:24:19)
Included patches: 1, 3-4, 7-9, 11, 13-17, 19-26, 29-31, 34-44, 47, 50-56, 58-64, 66-73, 75, 77-92, 94-107, 109, 202, 234-237
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):

As a workaround I'm running vim with the below commant:
$ VIMBLACKLIST='Y' vim

**Comment by tpope** [comment]
Are you using the latest from GitHub? The workaround has not made it into a stable release.

**Comment by ameidatou** [comment]
Yes I'm using the latest, and I checked the commit that closed the issue and it's in the version I'm using but vim still hangs.

**Comment by LeoGalleguillos** [comment]
Using pathogen with Vim 7.0 also hangs for me. The solution, as mentioned above, was:

export VIMBLACKLIST=Y
vim

I'm on CentOS 5, so Vim 7.0 is the latest version of Vim available for now. We'll upgrade to CenOS 6 or 7 sometime during 2016.

Any chance we could get a patch for this in the meantime?

**Comment by tpope** [comment]
Yes, please do send a patch.

**Comment by nschley** [comment]
With all due respect to @LeoGalleguillos, I think his solution is somewhat _shallow_, especially as this ticket is remaining open so for all intelligent civilization to review.  I propose the following revision, to incorporate a little _valuation_.

<pre>export VIMBLACKLIST=TIM.P_ROCKS
vim</pre>

Thanks for sharing your work, Tim!
