### ISSUE TITLE
Errors when running vim with Pathogen installed

### ISSUE THREAD

**Issue by byrongibson** [tpope/vim-pathogen#13]
I'm trying to install pathogen, but am getting a string of errors.  I've installed autoload/pathogen.vim and added the following to .vimrc (before the 'filetype plugin indent on' directive'):

<pre>
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()
</pre>

But when I open vim, I get the following command line errors:

 <pre>
me@me-desktop:~/.vim$ vim autoload/README 
Error detected while processing /home/me/.vim/autoload/pathogen.vim:
line    4:
E492: Not an editor command: ^M
line    8:
E492: Not an editor command: ^M
line    9:
E15: Invalid expression: exists("g:loaded_pathogen") || &cp^M
line  143:
E171: Missing :endif
line    4:
E492: Not an editor command: ^M
line    8:
E492: Not an editor command: ^M
line    9:
E15: Invalid expression: exists("g:loaded_pathogen") || &cp^M
line  143:
E171: Missing :endif
Error detected while processing /home/me/.vimrc:
line   72:
E117: Unknown function: pathogen#helptags
Error detected while processing /home/me/.vim/autoload/pathogen.vim:
line    4:
E492: Not an editor command: ^M
line    8:
E492: Not an editor command: ^M
line    9:
E15: Invalid expression: exists("g:loaded_pathogen") || &cp^M
line  143:
E171: Missing :endif
Error detected while processing /home/me/.vimrc:
line   73:
E117: Unknown function: pathogen#runtime_append_all_bundles
me@me-desktop:~/.vim$ 
</pre>

I've tried to get rid of the <pre>^M</pre> with a global replace: <pre>:%s/^V^M//g</pre>but the replace doesn't see any of them.  

Any suggestions what I'm doing wrong?

**Comment by rstecca** [comment]
With Notepad++ I set the encoding to UTF-8 and it worked for me.
