### ISSUE TITLE
Download of pathogen fails (curl SSL: certification verification failed)

### ISSUE THREAD

**Issue by ghost** [tpope/vim-pathogen#137]
Hi!

I know you hate to hear this based on recent issues but the curl command in the README (`curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim`) gives me a:

`curl: (51) SSL: certificate verification failed (result: 5)` error.

Even fails when I do `curl -O https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim`

It downloads only if I use http instead of https.

Any thoughts?

**Comment by antiusninja** [comment]
Hi. I'm pretty new to linux and stupid enough to not be able to setup things correctly. I just follow orders , but the curl -LSso.... command gives me
cur:(23) Failed writing body (O!= 12476).
Can you help me out?
