### ISSUE TITLE
Pathogen not loading bundles on OSX

### ISSUE THREAD

**Issue by Hippimuro** [tpope/vim-pathogen#150]
The first two lines of my .vimrc: 
`source /Users/me/.vim/autoload/pathogen.vim`
`call pathogen#infect()`

Without the `source` pathogen doesn't load and instead vim throws an error about unknown function. Pathogen doesn't load anything even if those two are the only lines in ~/.vimrc.

`:echo pathogen#glob('bundle/*')` returns `['bundle/rust.vim', 'bundle/tabular', 'bundle/vim-colors-solarized']`

**Comment by tpope** [comment]
Check `:set runtimepath?` before that and make sure it includes `/Users/me/.vim`.

**Comment by Hippimuro** [comment]
Ah, that was indeed the problem.

Thanks, and sorry for bothering.
