### ISSUE TITLE
syntax error in .vimrc for pathogen

### ISSUE THREAD

**Issue by nafooesi** [tpope/vim-pathogen#151]
-bash: .vimrc: line 1: syntax error near unexpected token \`('
-bash: .vimrc: line 1: `execute pathogen#infect()'

My .vimrc is simply this:
_____________________
    execute pathogen#infect()
    syntax on
    filetype plugin indent on
_____________________

**Comment by tpope** [comment]
With Vim running, can you report the output of

    :echo pathogen#infect()

**Comment by nafooesi** [comment]
Thanks for the quick response.   I checked, and it doesn't print anything. My .vim directory tree is the following:

/home/bchi/.vim
├── autoload
│   └── pathogen.vim
└── bundle
    └── vim-flake8

**Comment by tpope** [comment]
What's the first 5 lines of `:version`?

**Comment by nafooesi** [comment]
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled May  4 2012 04:25:35)
Included patches: 1-429
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):

**Comment by tpope** [comment]
Wait, why do those errors say `bash`? Those aren't vim errors at all.

**Comment by nafooesi** [comment]
The error was from "source ~/.vimrc" under bash, but I tried

":source ~/.vimrc" under vim, then 
":echo pathogen#infect()"

and it shows nothing.

**Comment by tpope** [comment]
Don't `source ~/.vimrc` in bash.

**Comment by nafooesi** [comment]
":source ~/.vimrc" under vim didn't make a difference.
How do I know if it loads pathogen?

**Comment by tpope** [comment]
Do your installed plugins work?
