### ISSUE TITLE
Pathogen does not work, when settings made in _gvimrc

### ISSUE THREAD

**Issue by marrue** [tpope/vim-pathogen#152]
I tried to use pathogen in my _gvimrc. All settings worked, except the pathogene. It did not load anything, even if I followed the instructions as given. When rename the _gvimrc to _vimrc pathogen worked as described. If this is not a bug, then it should be mentioned in the install-instructions.

**Comment by auscompgeek** [comment]
Why are you setting up vim to only run pathogen when you open a GUI?

Anywho, see https://github.com/tpope/vim-pathogen/issues/114#issuecomment-31900934.

**Comment by tpope** [comment]
Yeah the instructions say vimrc. I don't really want to muddle them with things *not* to do.
