### ISSUE TITLE
Question about using Pathogen on specific sub-directories

### ISSUE THREAD

**Issue by assarbad** [tpope/vim-pathogen#156]
Hi Tim,

first of all thanks for all the work you have put into your Vim plugins.

I'd like to ask for some information on Pathogen, hope the tracker is the correct place for this and you don't mind.

I'd like to use Pathogen conditionally on certain subfolders of `.vim/bundle` or in such case point it to another folder hierarchy altogether.

Pathogen currently gets to "infect" on Vim 7.0 and higher in my `.vimrc`. Now I'd like to add some color schemes into the mix. Since I use my dot files across different systems, I do not always have the latest Vim version available.

Is there a way to limit Pathogen's scope or point it to an additional folder to scan after I have already called infect?

Thanks,

Oliver

**Comment by tpope** [comment]
You can give `infect` multiple arguments. Does that take care of everything?

**Comment by assarbad** [comment]
Sorry for the noise. I feel stupid now :)

Yeah, that will do the job. Thanks a lot for your quick help.
