### ISSUE TITLE
pathogen#surround(...) produces extra / if used without {}

### ISSUE THREAD

**Issue by mkoskar** [tpope/vim-pathogen#157]
Wanting to add single plugin bundle to `runtimepath` I do following:

```
call pathogen#surround('~/.vim/bundle/colorschemes')
```  

If that directory exists `rtp`'s after directory path will contain `//`
(`~/.vim/bundle/colorschemes//after`). I haven't tested if that poses any
runtime problem (I suspect it does not). So this is then in "be nice"
category.

**Comment by lifepillar** [comment]
Same here. A problem is that, if you add more paths later, paths start to get truncated. For example:

```
:call pathogen#surround('~/.vim/bundle/youcompleteme')
:set rtp
runtimepath=~/.vim/bundle/youcompleteme/,~/.vim [...] ~/.vim/bundle/youcompleteme//after
:call pathogen#surround('~/.vim/bundle/foobar')
:set rtp
runtimepath=~/.vim/bundle/foobar, [...] ~/.vim/bundle/youcompleteme//after,~/.vim/bundle/foobar/afte
:call pathogen#surround('~/.vim/bundle/didgeridoo')
:set rtp
runtimepath=~/.vim/bundle/didgeridoo, [...] ~/.vim/bundle/youcompleteme//after,
```

**Comment by lifepillar** [comment]
Ah, there seems to be a typo here:

```
let path = fnamemodify(a:path, ':p:?[\\/]\=$??')
```

Shouldn't that be `':p:s?[\\/]\=$??'`?

**Comment by lifepillar** [comment]
See https://github.com/tpope/vim-pathogen/pull/160.

**Comment by tpope** [comment]
The truncation is a function of `:set` output. See `:echo &rtp`.

**Comment by lifepillar** [comment]
> The truncation is a function of `:set` output. See `:echo &rtp`.

Thanks, I was having a hard time trying to understand what was causing that!
