### ISSUE TITLE
https://tpo.pe/pathogen.vim NOT FOUND error

### ISSUE THREAD

**Issue by robes** [tpope/vim-pathogen#159]
The URL in the installation instructions here is not found on your server.

```sh
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
```

And anyway, why not point to the file in your github repo anyway.

```sh
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
```

Having said that. Thanks for this plugin. It's a great way of managing plugins!

**Comment by tpope** [comment]
Fixed, thanks. I used to point at the GitHub URL directly but I kept getting reports of failures I couldn't reproduce.
