### ISSUE TITLE
Commit e2f96de (Experimental: Support "vimfiles" subdirectory) broke snipmate

### ISSUE THREAD

**Issue by yann-morin-1998** [tpope/vim-pathogen#167]
Hello!

I'm using pathogen to autoload a few plugins, of which [vim-snipmate](https://github.com/garbas/vim-snipmate).

Today I update pathogen, to find that my snippets were no longer expanded. My other plugins
seem to still be loaded, though.

I've bisected the breakage to be with e2f96de (Experimental: Support "vimfiles" subdirectory).
Since I'm not very vim-script savvy (to say the least), I'm a bit lost at what to do now...

Regards,
Yann E. MORIN.

**Comment by tpope** [comment]
Check your `'runtimepath'` on each version and see if anything changed. You can get it into a buffer with `:call setline(1, pathogen#split(&rtp))`

**Comment by tpope** [comment]
Nevermind, I see what it is.

**Comment by yann-morin-1998** [comment]
Hi!

OK, here's the diff:

```
--- pathogen.OK	2015-12-22 18:31:51.208985272 +0100
+++ pathogen.KO	2015-12-22 18:32:25.957468290 +0100
@@ -6,12 +6,10 @@
 /home/ymorin/.vim/bundle/snipmate
 /home/ymorin/.vim/bundle/snippets
 /home/ymorin/.vim/bundle/tlib
-/home/ymorin/.vim/bundle/update.me
 /home/ymorin/.vim/bundle/vim-troll-stopper
 /var/lib/vim/addons
 /usr/share/vim/vimfiles
 /usr/share/vim/vim74
 /usr/share/vim/vimfiles/after
 /var/lib/vim/addons/after
-/home/ymorin/.vim/bundle/snipmate/after
 /home/ymorin/.vim/after
```

OK, two differences:
  - `update.me`: this one is OK, it's a file (a hint for my auto-update script to update sub-dirs).
  - `/home/ymorin/.vim/bundle/snipmate/after`: this one is the culprit, I guess.

Thanks!

**Comment by yann-morin-1998** [comment]
Aha! :-)
Thanks!

**Comment by yann-morin-1998** [comment]
Confirmed, it's fixed.
Thanks for the quick response! :-)
