### ISSUE TITLE
curl: (7) Failed to connect to tpo.pe port 443: Network is unreachable

### ISSUE THREAD

**Issue by trkrameshkumar** [tpope/vim-pathogen#168]
Hi @tpope ,

Getting this error on ubuntu, when try to install vim-pathogen,

``
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
``

so i replaced ``https://tpo.pe/pathogen.vim`` with ``https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim``

**Comment by tpope** [comment]
Presumably it was down but it's up now.

**Comment by trkrameshkumar** [comment]
@tpope
Soon after i got this error, i was trying to visit this url ''https://tpo.pe/pathogen.vim'' on browser it was opening at that time too, but even then got this error ``curl: (7) Failed to connect to tpo.pe port 443: Network is unreachable``that was the reason why i replaced this url ''https://tpo.pe/pathogen.vim'' with github raw code url  to install ``vim-pathogen``

**Comment by trkrameshkumar** [comment]
Anyway now i tried to reinstall vim-pathogen with short url , it is installing without any issue, Thanks for your reply

**Comment by LAAMU** [comment]
7
