### ISSUE TITLE
plugins not loading

### ISSUE THREAD

**Issue by zwhitchcox** [tpope/vim-pathogen#169]
I used the script 

```
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
```

and added `execute pathogen#infect()` to my vimrc, but it still is not loading plugins.

**Comment by Gankarloo** [comment]
Did you put your plugins under ~/vim/bundle/

**Comment by zwhitchcox** [comment]
I put them under `~/.vim/bundle/`

**Comment by Gankarloo** [comment]
Do you have both ~/.vim and ~/vim
You said you installed into ~/vim

**Comment by zwhitchcox** [comment]
No, I only installed pathogen to `.vim`. I added `execute pathogen#infect()` to `.vimrc`. I just used the script in the README: 

```
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
```

**Comment by zwhitchcox** [comment]
That is incorrect. I believe the client you are using is removing the dot from the file path.

**Comment by Gankarloo** [comment]
Indeed the . got lost somewhere between github and gmail.

**Comment by tpope** [comment]
Check `:set runtimepath?`

**Comment by zwhitchcox** [comment]
from `:set runtimepath`

```
runtimepath=~/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim
/vimfiles/after,~/.vim/after
```

**Comment by zwhitchcox** [comment]
fixed: was using vi instead of vim
