### ISSUE TITLE
vim freeze for a couple second 

### ISSUE THREAD

**Issue by pinggit** [tpope/vim-pathogen#172]
this is a weird issue.
whenever I save some of my file (not all), vim freeze for some notable seconds and continue.

I found this is related to:
* file type , currently I have two files that have this problem, both are with ft asciidoc, if I set to other file type , like tcl, issue will go away
* pathogen, if I remove this, issue will go:
```
execute pathogen#infect()
```

can you help to locate the issue?

**Comment by tpope** [comment]
Yeah, it's in one of the plugins that Pathogen is loading.

**Comment by pinggit** [comment]
is there a way to resolve/workaround this issue?
