### ISSUE TITLE
Reload every plugin as in vim-scriptease

### ISSUE THREAD

**Issue by dbeniamine** [tpope/vim-pathogen#173]
Hi,

I'm developing a vim plugin manager on top of pathogen called [vizardry](https://github.com/dbeniamine/vizardry), and at some points I need to reload every scripts (for instance after an upgrade).

Currently I'm able to Reload everything but the autoloaded files, I think you have implemented this in scriptease for the `:Runtime` command.

I was wondering if It was possible to move this command to pathogen or do something similar.

Bye,

David

**Comment by tpope** [comment]
I might add reloading some day, but it would take a lot more work than just ripping the corresponding development tools out of scriptease. If you want to leverage that functionality in the meantime, I recommend copy and paste.
