### ISSUE TITLE
Using plugins globally

### ISSUE THREAD

**Issue by joergklein** [tpope/vim-pathogen#175]
I've installed some plugins via pathogen.
Install pathogen:
mkdir -p ~/.vim/autoload ~/.vim/bundle && \ curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

Install syntastic as pathogen bundle:
cd ~/.vim/bundle && git clone https://github.com/scrooloose/syntastic.git

At this point it's in ~/.vim directory of my root user.
I'd like to install this plugin to be globally available for all users on the box, but I'm having trouble finding out how to go about doing it. All the instructions seem to talk about installing plugins under $HOME/.vim or in my case under ~/.vim. What have I to do that all user can use the plugins out of the box?

I am using centos 7

**Comment by tpope** [comment]
`/usr/share/vim/vimfiles` will work for most setups.

**Comment by coolaj86** [comment]
For those of us that need a little hand-holding:

```
mkdir -p /usr/share/vim/vimfiles/autoload /usr/share/vim/vimfiles/bundle && \
curl -LSso /usr/share/vim/vimfiles/autoload/pathogen.vim https://tpo.pe/pathogen.vim

pushd /usr/share/vim/vimfiles/bundle
git clone git://github.com/tpope/vim-sensible.git
git clone https://github.com/scrooloose/syntastic.git
popd
```

**Comment by seisowl** [comment]
On Ubuntu 18.04, it's /usr/share/vim/addons/plugin
Also,to install pathogen, use:
sudo apt install -y vim-pathogen
