### ISSUE TITLE
Do not recommend the use unauthenticated git cloning

### ISSUE THREAD

**Issue by ypid** [tpope/vim-pathogen#179]
The README gives an example like this:

```shell
cd ~/.vim/bundle && \
git clone git://github.com/tpope/vim-sensible.git
```
which should really be:

```shell
cd ~/.vim/bundle && \
git clone https://github.com/tpope/vim-sensible.git
```

The problem is that the git protocol has no message authentication.

This issue seems to also effect your Vim plugins.

**Comment by tpope** [comment]
It's actually been on my todo list to replace all my URLs with a hosting agnostic redirect. Something like

    git clone https://tpope.io/vim/sensible.git

**Comment by ypid** [comment]
> It's actually been on my todo list to replace all my URLs with a hosting agnostic redirect.

Sounds good. In that case you could maybe even completely self host the mirror instead of redirecting?
