### ISSUE TITLE
Access to pathogen.vim via https://tpo.pe/pathogen.vim not working

### ISSUE THREAD

**Issue by baogorek** [tpope/vim-pathogen#183]
My script that gets pathogen.vim this every day stopped working, and I noticed I can't access [the link](https://tpo.pe/pathogen.vim) from a browser either. Of course a workaround is to get it directly from the repo, but it'd be nice to have the link working again (and the installation instructions reference it.)

**Comment by tpope** [comment]
Thanks, fixed.

**Comment by d5ve** [comment]
https://tpo.pe/pathogen.vim is timing out for me now too.

Is it worth updating the instructions to point to https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim ?

Cheers,

Dave

**Comment by tpope** [comment]
Was doing some server maintenance. Should be back up.
