### ISSUE TITLE
Unknown function: pathogen#infect

### ISSUE THREAD

**Issue by vitaly-zdanevich** [tpope/vim-pathogen#184]
Because I trying to move `~/.vim` to the `~/.config/vim`. I need to change some env for Pathogen?

**Comment by tpope** [comment]
I don't know where you got `~/.config/vim` from. If you're running Neovim, it should be `~/.config/nvim`.

**Comment by vitaly-zdanevich** [comment]
It is possible to move `~/.vim` to any other place?

**Comment by scottwhudson** [comment]
I just wrote a shell script to automate my vim installation and I ran into this error as well using the default file configuration:

**install.sh**
```
echo 'cloning pathogen'
git clone https://github.com/tpope/vim-pathogen.git ~/.vim/autoload/pathogen.vim

echo 'cloning ctrl-p'
git clone https://github.com/ctrlpvim/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim

echo 'cloning nerdtree'
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
```

**.vimrc**
```
execute pathogen#infect()
set nocompatible
syntax on
filetype plugin indent on
set ts=2 sts=2 sw=2 expandtab
```

**error message**
```
Error detected while processing /Users/swh_personal/.vimrc:
line    1:
E117: Unknown function: pathogen#infect
E15: Invalid expression: pathogen#infect()
Press ENTER or type command to continue
```

**Comment by tpope** [comment]
You're cloning a directory to a filename.

**Comment by scottwhudson** [comment]
Ah, duh... Thanks.

**Comment by argentum47** [comment]
https://github.com/argentum47/vim-rust-ide/
My ^ setup works with vim not with neovim. What am I missing. I get the same `Unknow function pathogen#infect` error. also I updated the version of pathogen in my autoload.

**Comment by tpope** [comment]
In Neovim you need to install in `~/.config/nvim` instead (or add `~/.vim` to your runtime path).
