### ISSUE TITLE
Question: Keeping on top of updates to Pathogen.vim

### ISSUE THREAD

**Issue by mskadu** [tpope/vim-pathogen#185]
Firstly, thank you for this _excellent_ script to help with automating my vim package management. 

I am trying to automate my vim config+plugins management on Windows. I am using [github](https://github.com/mskadu/dotfiles) to version control my changes across machines. 

As per your instructions, 
* the pathogen module placed under %USERPROFILE%\vimfiles\autoload\ 
* any packages I need are kept under %USERPROFILE%\vimfiles\bundle and configured as git submodules

And this works without a hitch. 

The question - is there a way I can stay on top of it's latest revision (ideally via github)? I thought about git-cloning it into %USERPROFILE%\vimfiles\autoload, but that will create a sub-folder called autoload in there - which I don't think would be right?

Hope this makes sense?

**Comment by shmcgrath** [comment]
This is from the FAQ in the README:

**Can I put pathogen.vim in a submodule like all my other plugins?**
Sure, stick it under ~/.vim/bundle, and prepend the following to your vimrc:

`runtime bundle/vim-pathogen/autoload/pathogen.vim`

I have my Pathogen set up this way. I manage it will all the rest of the submodules.

**Comment by tpope** [comment]
Yep!

**Comment by mskadu** [comment]
Sounds like a good idea. Thanks!

--
Mayuresh
