### ISSUE TITLE
Please accomodate fixed-column comment formats

### ISSUE THREAD

**Issue by jkulesza** [tpope/vim-pathogen#188]
I recently came across [this fork](https://github.com/foodbag/vim-commentary) of vim-commentary that handles the functionality I'm looking for: forcing vim-commentary to insert the comment character in a particular column.  In this instance, new variables are introduced: `g:commentary_fixed` and `g:commentary_fixed_pos`.

It doesn't look like the author has made a pull request, but I hope you might consider adding it to your own plugin with proper attribution.

**Comment by tpope** [comment]
Wrong repo.
