### ISSUE TITLE
Header link is broken.

### ISSUE THREAD

**Issue by thejohnbackes** [tpope/vim-pathogen#194]
http://www.vim.org/scripts/script.php?script_id=2332 leads to 504 Gateway Timeout (nginx)

**Comment by xaizek** [comment]
It's not broken, it's site of Vim which is down. It's hosted on SourceForge, which apparently has some technical issues. I doubt tpope can do anything about it.

**Comment by tpope** [comment]
Thanks for the heads up regardless. I'm sure it will be back up soon enough.
