### ISSUE TITLE
Can pathogen load plugins in the bundle directive before loading the scripts in vim root directive?

### ISSUE THREAD

**Issue by huangzonghao** [tpope/vim-pathogen#197]
It seems the pathogen always try to load the scripts in the `vim/ftplugin` first, before loading the scripts in `vim/bundle/myplugin/ftplugin`.

I am wondering if there is a way that I can load the latter first? Because I always want to put the customized configurations for the third-party plugin in the `vim/ftplugin`  directive. But if the corresponding scripts of plugin hasn't been loaded yet, my configuration won't succeed, due to problems like "undefined variable", etc.

**Comment by tpope** [comment]
Vim provides a directory your customized configurations: `vim/after/ftplugin`.

**Comment by huangzonghao** [comment]
Oh thank you so much! Can't believe I didn't know this before!
