### ISSUE TITLE
Pathogen broken by new release of Vim

### ISSUE THREAD

**Issue by frioux** [tpope/vim-pathogen#199]
Fair warning, I have no idea what's going on.  I installed a new version of vim and pathogen is failing to parse.  I am 90% sure that the error is due to a bug in vim, but do not know.  Figured you'd want to be aware.  Full details are here: https://groups.google.com/forum/#!topic/vim_use/94wo-ZiqJwo

**Comment by tpope** [comment]
The stacktrace appears to be pointed at this line:

    let blacklist = get(g:, 'pathogen_blacklist', get(g:, 'pathogen_disabled', [])) + pathogen#split($VIMBLACKLIST)

You could try running pieces of that line to isolate the issue. My wild guess would be that undefined environment variables are handled differently.

**Comment by frioux** [comment]
Hilarious.  Turns out that your fix in august last year resolves this.  Upgrading pathogen fixed it.  Thanks and sorry for the noise.

**Comment by frioux** [comment]
e7857bed4e0705f91f781dbe99706f07d08d104b, for the curious
