### ISSUE TITLE
Cannot use `-` on staged or untracked files in `:Gstatus`

### ISSUE THREAD

**Issue by TSFoster** [tpope/vim-pathogen#201]
Hi,

Hitting `-` on staged or untracked files does nothing in `:Gstatus` (works fine for tracked files with changes). I'm running git v2.18.0 on MacOS 10.13.6. `dp` also doesn't work on untracked files.

This happened when using Nvim v0.3.1/fish v2.7.1, but the same thing happens when using Vim v8.0/bash v3.2.57 and with a minimal vimrc (pathogen + fugitive).

**Comment by TSFoster** [comment]
@tpope Yup

**Comment by tpope** [comment]
Okay open this issue on the correct repo.
