### ISSUE TITLE
curl error(23)

### ISSUE THREAD

**Issue by Viceeee** [tpope/vim-pathogen#204]
I got this error today
curl: (23) Failed writing body (0 != 1918)

**Comment by tpope** [comment]
Is it still happening? It's working fine for me so I'm guessing this was a temporary issue.

**Comment by hosseinhaeri** [comment]
I tried following the installation guides and I do get it: (PowerShell 7.10 under Windows 10)

mkdir -p ~\vimfiles\autoload, ~\vimfiles\bundle && curl -LSso ~\vimfiles\autoload\pathogen.vim https://tpo.pe/pathogen.vim

    Directory: C:\...\vimfiles

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          16/11/2020    10:57                autoload
d----          16/11/2020    10:57                bundle
curl: (23) Failed writing body (0 != 1371)
