### ISSUE TITLE
`:Helptags` does not work if script is never run

### ISSUE THREAD

**Issue by joshklod** [tpope/vim-pathogen#205]
Now that Vim has native package support, I don't always call `pathogen#infect()`, but I would still like to use the `:Helptags` command.  But because the autoload script is never executed, the command is never added.

Maybe the `:command Helptags ...` should be in `plugin/pathogen.vim`?  The downside of this is installation is no longer as super-simple.

Alternatively, the whole file could move into `plugin/`.  Most people run it first thing in their `.vimrc` anyway.  My particular scenario happens to be the worst case for needlessly loading.

**Comment by tpope** [comment]
`:Helptags` was always intended to be called interactively. If you really must generate help tags on every startup, you can `call pathogen#helptags()`.

**Comment by tpope** [comment]
I misread, you do want to call it interactively. You can `runtime! autoload/pathogen.vim` in your vimrc. I'm not changing changing the installation method this late in the game.

**Comment by joshklod** [comment]
You misunderstand. I want to *add* the command on every startup, not *call* it.

**Comment by joshklod** [comment]
> I'm not changing changing the installation method this late in the game.

Fair enough.
