### ISSUE TITLE
Disable plugin without deleting it's repo

### ISSUE THREAD

**Issue by chinmaychhajed** [tpope/vim-pathogen#207]
Hello,

How do I disable a plugin without deleting it's repository? Is there any command which can be added in `.vimrc` which will disable a plugin?  It's very tedious to `mv` a plugin so as not to use it temporarily.
Thanks in advance.

**Comment by xaizek** [comment]
https://github.com/tpope/vim-pathogen/blob/e9fb0914dba5bdfe2feaa364dda2e9495c5620a2/autoload/pathogen.vim#L99-L101

Appending `~` to a directory name also disables the plugin:

https://github.com/tpope/vim-pathogen/blob/e9fb0914dba5bdfe2feaa364dda2e9495c5620a2/autoload/pathogen.vim#L103

**Comment by chinmaychhajed** [comment]
Can you show an example to add multiple plugins to `g:pathogen_blacklist`. I assume adding names to this also disables them

**Comment by xaizek** [comment]
Adding this before calling `pathogen#infect` disables both mentioned plugins for me:
```vim
let g:pathogen_blacklist = [ 'commentary', 'fugitive' ]
```

**Comment by chinmaychhajed** [comment]
Thanks, that worked. Btw pls change `fugitive` to `vim-fugitive` to refer in future as I use fugitive and copied line in your previous command to check if it's working. After some time I relaised that it's not `fugitive` but `vim-fugitive`!
