### ISSUE TITLE
Please document how to work around vim bug using  the vim package format (Not directly related to pathogen)

### ISSUE THREAD

**Issue by mowgli** [tpope/vim-pathogen#212]
I use pathogen for many years now. Recently, I migrated, motivated by the notice in your readme, to the native package format in vim.

Unfortunately that made at least one plugin, fugitive, not working correct anymore. The bindings in blame window are broken now.

So could you please document one or both of the following?
1. Add a warning to users that vim packages might not work correctly.
2. Add a hint how to mitigate that bug(s) in vim with pathogen. (Maybe one can use `execute pathogen#infect('bundle/{}', 'pack/{}/start/{}')` to mitigare that. I did not chek until now if that work)

**Comment by tpope** [comment]
I personally use Fugitive in this exact setup without issue. Without knowing what's going wrong on your machine, I don't think there's anything to be done here.
