### ISSUE TITLE
whitespace required errors

### ISSUE THREAD

**Issue by gedge** [tpope/vim-pathogen#215]
seeing this with a new vim version
```
Error detected while processing /Users/gedge/.vimrc[45]..function pathogen#infect[17]..pathogen#interpose:
line   10:
E1004: White space required before and after ':'
```

fixed in #214

**Comment by gedge** [comment]
also may have been fixed in https://github.com/vim/vim/commit/a04d447d3aaddb5b978dd9a0e0186007fde8e09e

**Comment by chrisbra** [comment]
this is a vim bug, that has been fixed.

**Comment by tpope** [comment]
Merged anyways, no harm in supporting this one weird patch level of Vim.
