### ISSUE TITLE
How to tell pathogen to ignore specific file in bundle?

### ISSUE THREAD

**Issue by dragon-architect** [tpope/vim-pathogen#222]
I'm attempting to bundle up the group of scripts I've split my vim configuration into so I can `execute pathogen#infect('~/.vim/rcfiles')` and be able to load everything as well as my own help docs, templates, etc., but one of the files, `vimrc.vim` is the base config that contains the calls for pathogen to infect vim. I need to explicitly ignore this specific file to avoid recursion. I cannot discern how to do this from the extremely limited documentation that exists in the source comments. How can this be done?

**Comment by tpope** [comment]
Pathogen adds directories to `'runtimepath'`. It doesn't operate on files at all. Recursion is impossible.
