### ISSUE TITLE
pathogen won't load colorschemes

### ISSUE THREAD

**Issue by dbb** [tpope/vim-pathogen#57]
I followed these instructions on installing a colorscheme to the bundle:

```
git clone https://github.com/jelera/vim-gummybears-colorscheme ~/.vim/bundle

# some proof that the file is there
ls .vim/bundle/colors 
gummybears.vim
```

This is how I'm calling pathogen in my vimrc

``` viml
call pathogen#runtime_append_all_bundles()
filetype off
syntax on
" turn filetype back on
filetype indent plugin on
```

As described here: http://stackoverflow.com/questions/3383502/pathogen-does-not-load-plugins

I also tried installing this colorscheme in bundle: http://ethanschoonover.com/solarized/vim-colors-solarized

Vim is insisting that I have no colorscheme called gummybears or solarized.

**Comment by denzuko** [comment]
Current version of pathogen use pathogen#infect() instead of pathogen#runtime_append_all_bundles().
